### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [cazitouni/QgisGLViewer#1]
# Problem

Please change the plugin homepage link in metadata.txt to reference this repo if you do not have a dedicated page on your website.

Also update the plugin repository with a new zip so that those changes are visible before we approve

**Comment by cazitouni** [comment]
Hello, Thanks for your review, it's done.
Do not hesitate to contact me if there is any other issues.

**Comment by Palohort** [comment]
Good day
This plugin doesn't want to work for me. It warns that: "No image for this coordinates".
I tried to put the point layer of the photo geometry into WGS 84 and World Mercator, but without success.
I have QGIS version 3.28.2. on OS Windows 10 Pro.
How would I know what the problem is? I set everything correctly according to your instructions.
Thank you.
Pavol Hort
<img src="https://user-images.githubusercontent.com/123732809/215065210-62e633c6-c226-4dd4-869a-473ab0d5a7cd.png" width="100" height="100">

**Comment by cazitouni** [comment]
Hello @Palohort,
Is it possible for you to provide me a sample of your layer with a few photos to test it  ?
I dind't have the possibility atm to test with different photo sets. 
Thanks you, Kind regards, Clément.

**Comment by Palohort** [comment]
I am attaching the first 7 photos for size and point layer (gpkg).
Thank you for your reply
Pavol
[Panorama_data.zip](https://github.com/cazitouni/QgisGLViewer/files/10518518/Panorama_data.zip)

**Comment by cazitouni** [comment]
@Palohort  Thanks for the sharing.
Indeed, there is a bug due to the qdate column format for your date column. 
I will pack a fix in the next version but it could takes several days for the upload to go on the Qgis repository. 
In the meantime you can try to make a new date column in text format it should work. 
I tried with the original EPSG:3857 and it works on my machine. 
![image](https://user-images.githubusercontent.com/92778930/215085200-f4711389-8135-49fb-9a5a-467dddbcfb83.png)
Do not hesitate to contact me if it does not work or if you have other problem. 
And tell me if it works for you aswell !
Thank you, Regards, Clément.

**Comment by Palohort** [comment]
Yes, now it works for me. Thanks!
