### ISSUE TITLE
Permission denied on resetting connection 

### ISSUE THREAD

**Issue by gacquier** [cazitouni/QgisGLViewer#4]
Hi,
Thanks for this great plugin !

I first tested it an managed to get it to work, except the direction field was weird (miscalcultation on my side). After updating the direction field in a new geopackage, I tried to reset the connection and got this error : 

> 2023-03-30T12:04:33     WARNING    Traceback (most recent call last):
>               File "C:\Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisGLViewer\Windows.py", line 134, in save_connection
>               with open("connection_params.json", "w") as f:
>              PermissionError: [Errno 13] Permission denied: 'connection_params.json'
> 

I tried to restart QGIS, uninstall / Reinstall the plugin, restart my PC, change the geopackage location... Still having this error now..

I could'nt find any file named "connection_params.json" on my computer..

Would you have a hint on what I could have done wrong ?

**Comment by cazitouni** [comment]
Hello  @gacquier,

It seems that the plugin can't acces the connection_params.json file, on windows by default the file is created in the user "Documents" folder.

It's possible that your organisation set a more restrictive acces control to this folder. 

I will look into it to place the file at the root of the plugin instead of Document folder. I keep you in touch.

Thanks for using my plugin, 
Kind Regards, Clément.

**Comment by gacquier** [comment]
Thanks a lot for your fast awnser !

Indeed, I tried to run QGIS as administrator and it worked...

I do not think that my organisation has such complicated strategies... Moreover, it worked great at first, even in normal mode....

I'll tell you if I get some more information / explanations.

Thanks again for developing and maintaining this great plugin !
Géraud

**Comment by cazitouni** [comment]
Hello @gacquier,

I've updated the plugin with a fix, now the file should be created in the user profile's folder. 
Would you try with the attached zip version (1.3.1) and let me know if the bug is fixed for you  ?

Thank you,
Regards, Clément. 
[QgisGLViewer.zip](https://github.com/cazitouni/QgisGLViewer/files/11139232/QgisGLViewer.zip)

**Comment by gacquier** [comment]
Hi,
Thanks a lot ! This fixed my problem !
Regards,
Géraud

**Comment by cazitouni** [comment]
Nice, then I close the issue and I'll deploy the new version to the main repo in a few days. 

Thanks for your feedback.
