### ISSUE TITLE
Error - "No image for this coordinates."

### ISSUE THREAD

**Issue by ibdmn** [cazitouni/QgisGLViewer#5]
I do have a similar issue as @Palohort mentioned in the other discussion thread. "No image for this coordinates."
After checking your solution, I also tried to modify my date column, as time and date were listed in different columns. This did hoever not fix the issue. My QGIS version is 3.30.1 and I do have the latest version 1.3.1 of your plugin.

I have also attached sample data - had however to remove the path since it contained customer related information.
[panorama_testfiles.zip](https://github.com/cazitouni/QgisGLViewer/files/11259206/panorama_testfiles.zip)

**Comment by cazitouni** [comment]
Hello @ibdmn,

Thanks for using my software, 
I've tried your sample datas and it worked for me (at least on the 5 images that are here). 

![image](https://user-images.githubusercontent.com/92778930/232832406-e577a32e-335e-40ba-96e9-1624e256e84b.png)

I've used this parameters (I've used the Comment column to adapt the path to my local install) 
![image](https://user-images.githubusercontent.com/92778930/232832796-ea9f45ee-33d8-4dc4-a516-505f5b5c78d8.png)

Only thing that seems a bit off is the azimuth param because the map canvas indicator is not aligned with the image. 

Did you make sure that your data(EPSG:4326) are in the same projection as your Qgis project ?
Also, you may want to try to use an absolute path instead of a relative one. 

Let me know if it help you a bit. 

Thanks in Advance,
Kind regards, Clément.

**Comment by ibdmn** [comment]
Hello Clément, 
thanks for the answer. It was indeed the projection in QGIS. I didn't think this could be an issue, since other plugins I used always worked. But I think the other plugins requested points from a layer while your plugin seems to be using the coordinates from the mouse cursor?

I realized the issue with the azimuth now aswell, seems like it is rotated 90 degrees for some reason. But that can be fixed. I do however not know, if I can transform all the data (images) from EPSG:4326 to EPSG:25832 (UTM32N). And we have to work with the EPSG:25832 in our projects.

And one more thing: With your plugin I can only connect to one PostGIS or geopackage at a time. Is there a plan to connect to multiple PostGIS tables / geopackages? 

Thanks for your work!
Best regards, Manuel

**Comment by cazitouni** [comment]
Hello Manuel , 

Im glad the solution works for you, to anwser your questions, 

1- The plugin make a request at the point you click on the map to get the closest point in the database within a 5m radius depending on the coordinate at clicking point, it also orient the image depending the direction you pulled while the click was maintained. 
2- For the north angle, I should investigate it may be related to the projection 4326 not handling the north angle the same as a projected meter projection(0° east/counter clockwise)  
3- You can indeed use your local projection with the plugin, but you'll need to reproject the layer accordingly, it's possible to do that directly in Qgis in the Vector menu 
![image](https://user-images.githubusercontent.com/92778930/233012495-d1162d71-2dd8-4e15-a5e6-6b9cde9b5558.png)
4- There is no plan actually to connect multiple databses at the same time, I've first made this plugin for our specific usecase at Strasbourg Eurometropolis but it could be a potential upgrade for future updates. 

I will look into the north angle problem since another user got it on his dataset, but I develop this plugin mostly on my free time so I cannot guarantee any delivery date. 

Anyway thanks for your feedback and using my plugin, I let the issue open for now let me know if you have any other questions. 

Kind regards, Clément.

**Comment by ibdmn** [comment]
Hello Clément,

Thank you again for the quick response!

To your 2- point:
I am playing around myself right now, trying to find a solution. Being able to "move" around by clicking in the pictures would be amazing for us!

To your 3- point:
Makes sense again, I just thought the plugin worked different. It does now work perfectly in our projects, thanks for that.

To your 4- point:
I'm trying to work around that now by creating a larger gepackage which combines all the information of the smaller geopackes we use so far. Since all the paths are already absolute paths there should not be an issue with displaying the right images.

Looking forward to hear from your updates and once again thank you for the plugin.

Kind regards, Manuel

**Comment by cazitouni** [comment]
I've looked a bit and Indeed it seems the angle is handled differently in epsg 4326, a solution that seems to work is to convert your actual azimuth like this (using the north column and Qgis field calculator for example) : 360 - ("azimuth" - 90), it may not be super accurate but it seems to work. north angle handling is still super annoying to me because of all the different projections that exists around the world .

Then you can move in the image, to move you can simply click on the image it takes the gap and the direction (blue line) and made a new request then load the image. So, if the azimuth is correct it should work as intended.

There should be no problem using a large geopackage for the plugin, I use a postgis layer with 1 million+ entries, you didnt have to load the layer in Qgis as well, even if it could be more practicle to see the points. 

Let me know if it helped.

Regards, Clément.

**Comment by ibdmn** [comment]
Larger geopackage is working fine for now, might move the layer into a postgis database if needed. Your calculation with "360 -("azimuth" - 90) worked best so far. It's not perfect yet, but good enough for now. The data probably contains minor errors in the azimuth anyway, so I'm happy with the result now.

Thanks again and best regards, Manuel

**Comment by ibdmn** [comment]
Hello Clément,

I now tried to install the plugins for all my colleagues, but some get this error:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/131141848/233931106-504c37e8-c1c2-40db-9940-05a4b6074ae3.png)

Any idea on what the issue might be here?

**Comment by cazitouni** [comment]
Hello Manuel, 
It's indeed strange it seems the plugin can't find opengl, but it's suposed to be installed by default in Qgis on Windows.
One solution could be to install the package pyopengl yourself using osgeo4w console [like this](https://landscapearchaeology.org/2018/installing-python-packages-in-qgis-3-for-windows/) or I tried to make a version with pyopengl packed with the plugin this should work as well 
[QgisGLViewer.zip](https://github.com/cazitouni/QgisGLViewer/files/11308036/QgisGLViewer.zip)

Let me know if its help, kind regards, Clément.

**Comment by ibdmn** [comment]
Hello Clément,
Sorry for the late notice, but yes the .zip helped and the plugin is now installed for all my colleagues.

Just now another small thing came up:
as previously mentioned, we use a geopackage for now that contains all the information needed.
One colleague however always has to browse through dirctories to then again assign the geopackage to the plugin, while for myself and other colleagues the path is saved in the plugin. Any ideas on that? 
Or do you think using PostGIS would be better in that situation?

Best regards, Manuel.

**Comment by cazitouni** [comment]
Ok i'm glad it helped, Qgis still pack opengl by default, I've checked on a fresh install of Windows so it's still strange that your colleagues doesn't have it. 
For the geopackage path I will look into it, the plugin is supossed to store the path and other information in a file called connection_param.json in qgis root directory in Roaming.
Postgis is better if you have collaborative work to do because geopackage can be write lock if another user modify it. 

I leave the issue open for this and because I need to update the north angle for EPSG 4326 as well. 

Thanks for your feedback, 
Regards, Clément.

**Comment by cazitouni** [comment]
Hello @ibdmn , 

Problem with EPSG:4326 should be now solved with version 1.3.2, I auto apply the formula for the bearing when the layer is in 4326. 

Same for the geopackage path, it was a bug, the geopackage path wasn't loading if there was no postgis parameters before. 

I've uploaded the new version in the main repo, it will be here in a few days since it require aproval before. 

I close the ticket for now. 

Do not hesitate to contact me if you have any other issues/suggestions. 

Kind regards, Clément.
